[package]
name = "snow-64"
version = "0.0.1"
authors = ["harmless-tech"]
edition = "2018"
description = "An fantasy console."
documentation = "TODO URL"
readme = "README.md"
homepage = "TODO URL"
repository = "https://github.com/harmless-tech/snow-64"
# license = "MIT License - Copyright (c) 2021 Harmless_Tech"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
log = "0.4.14"
log4rs = "1.0.0"
rhai = "0.19.15"
game-loop = "0.7.3"
lazy_static = "1.4.0"
rand = "0.8.3"
macroquad = "0.3.0-alpha.17"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
