name: Rust Release Build and Test

on:
  push:
    tags:
      - "v**"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    # Should this be a draft?
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: '^v[[:digit:]][[:digit:]]*\.[[:digit:]][[:digit:]]*\.[[:digit:]][[:digit:]]*$'
          prerelease_regex: '^v[[:digit:]][[:digit:]]*\.[[:digit:]][[:digit:]]*\.[[:digit:]][[:digit:]]*/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Vcpkg
        run: |
          cargo install cargo-vcpkg
          cargo vcpkg build
      - name: Build
        run: cargo build --verbose --workspace --release
      - name: Run tests
        run: cargo test --verbose --workspace --release
      - name: Add artifacts to GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: |
            target/release/snow-64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    needs: [ release ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Vcpkg
        run: |
          cargo install cargo-vcpkg
          cargo vcpkg build
      - name: Build
        run: cargo build --verbose --workspace --release
      - name: Run tests
        run: cargo test --verbose --workspace --release
      - name: Add artifacts to GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: |
            target/release/snow-64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    needs: [ release ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Vcpkg
        run: |
          cargo install cargo-vcpkg
          cargo vcpkg build
      - name: Build
        run: cargo build --verbose --workspace --release
      - name: Run tests
        run: cargo test --verbose --workspace --release
      - name: Add artifacts to GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: |
            target/release/snow-64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
